[FEAT] 사진 삭제 기능 구현
TeamPhotoSurfer/PhotoSurfer-Server pull request #22
Opened 2022-07-14 17:26 UTC by coreminw

2022-07-17 04:57 UTC, junjuning requested changes
코드 수정 후 말해주세요:)

2022-07-17 04:57 UTC, junjuning commented on src/controllers/PhotoController.ts
>      const likeResult = await photoService.test(client);
변수명 likeResult 말고 다른거 변경부탁이염

2022-07-17 04:57 UTC, junjuning commented on src/controllers/PhotoController.ts
> +const putPhoto = async (req: Request, res: Response) => {
조금 더 직관적일 수 있도록 deletePhoto는 어떠한가요!?

2022-07-17 04:57 UTC, junjuning commented on src/services/PhotoService.ts
> +const putPhoto = async (client: any, photoIds: any[]) => {
any?@@?@??!?!?!?!!?!?!?!?!?!??!?!?!?!?!?!?! 제가 한거 참고해서 변경 부탁:)

2022-07-17 04:57 UTC, junjuning commented on src/services/PhotoService.ts
> +  console.log(photoIdArr);
콘솔로그 지우셈ㅋㅋ

2022-07-17 04:57 UTC, junjuning commented on src/services/PhotoService.ts
> +  );
생각도 못하고 있던 in !! 나도 리팩해야징

2022-07-17 04:57 UTC, junjuning commented on src/services/PhotoService.ts
> +  );
요기 코드 확인 부탁!

2022-07-17 06:15 UTC, coreminw commented on src/controllers/PhotoController.ts
>      const likeResult = await photoService.test(client);
저거 테스트 코드인데 그냥 지울까요??

2022-07-17 06:16 UTC, coreminw commented on src/controllers/PhotoController.ts
> +const putPhoto = async (req: Request, res: Response) => {
바로 수정 했습니다 감사합니다 지_윤님:)

2022-07-17 06:54 UTC, coreminw commented on src/services/PhotoService.ts
> +  );
지원이의 도움을 받았읍니다..

2022-07-18 07:13 UTC, junjuning requested changes
잘하고있다 김미눅

2022-07-18 07:13 UTC, junjuning commented on src/services/PhotoService.ts
> +  }
select id하고 
```
if(!checkPhotoExist[0]){
}
```
하면 쉽게 해결할 수 있답니다! 참고!

2022-07-18 07:13 UTC, junjuning commented on src/services/PhotoService.ts
> +  );
푸시가 없는 경우는 에러나지 않나요!?!? 로직을 처리해줘야 할 것 같은데??

2022-07-18 07:25 UTC, coreminw commented on src/services/PhotoService.ts
> +const putPhoto = async (client: any, photoIds: any[]) => {
any 수정 완료용~~👍

2022-07-18 07:25 UTC, coreminw commented on src/services/PhotoService.ts
> +  console.log(photoIdArr);
바로 지웠습니다~ㅎ,,

2022-07-18 07:25 UTC, coreminw commented on src/services/PhotoService.ts
> +  );
확인완료!

2022-10-07 04:29 UTC, closed without merging