Feature/#80
TeamPhotoSurfer/PhotoSurfer-Server pull request #84
Opened 2022-09-27 08:22 UTC by coreminw

2022-09-28 02:04 UTC, junjuning requested changes
동작하나요,,?

2022-09-28 02:04 UTC, junjuning commented on src/modules/jwtHandler.ts
> +// };
주석은 야무지게 지워주세여!

2022-09-28 02:04 UTC, junjuning commented on src/services/AuthService.ts
>    );
db보니까 refresh_token 필드에 들어간게 없던데,,테스트 해보셨는가요,,,

2022-09-29 10:46 UTC, coreminw commented on src/services/AuthService.ts
>    );
지금 다시 구현해서 올렸습니다!!

2022-09-29 10:48 UTC, coreminw commented on src/modules/jwtHandler.ts
> +// };
알겠습니다~~!

2022-10-07 04:29 UTC, closed without merging